# These settings are synced to GitHub by https://probot.github.io/apps/settings/

repository:
  # Either `true` to make the repository private, or `false` to make it public.
  private: true

  # Either `true` to enable issues for this repository, `false` to disable them.
  has_issues: true

  # Either `true` to enable projects for this repository, or `false` to disable them.
  # If projects are disabled for the organization, passing `true` will cause an API error.
  has_projects: true

  # Either `true` to enable the wiki for this repository, `false` to disable it.
  has_wiki: false

  # Either `true` to enable downloads for this repository, `false` to disable them.
  has_downloads: true

  # Updates the default branch for this repository.
  default_branch: master

  # Either `true` to allow squash-merging pull requests, or `false` to prevent
  # squash-merging.
  allow_squash_merge: false

  # Either `true` to allow merging pull requests with a merge commit, or `false`
  # to prevent merging pull requests with merge commits.
  allow_merge_commit: true

  # Either `true` to allow rebase-merging pull requests, or `false` to prevent
  # rebase-merging.
  allow_rebase_merge: false

# Labels: define labels for Issues and Pull Requests
labels:
  # default labels
  - name: bug
    color: d73a4a
    description: Something isn't working

  - name: documentation
    color: 0075ca
    description: Improvements or additions to documentation

  - name: enhancement
    color: a2eeef
    description: New feature or request

  - name: task
    color: "312389"
    description: A small unit of work that can be part of an enhancement or bug

  # status labels
  - name: blocked
    color: e8617c
    description: This is currently blocked by another issue

  - name: waiting
    color: f29a82
    description: This is currently waiting for an event outside of our control to happen

  # priority labels
  - name: P1
    color: b60205
    description: Critical priority issue that must be resolved immediately
  - name: P2
    color: d93f0b
    description: Urgent priority issue that should be resolved before the next release
  - name: P3
    color: f48352
    description: Medium priority issue that needs to be resolved
  - name: P4
    color: fdea9b
    description: Low-priority issue that needs to be resolved
  - name: P5
    color: fcf3da
    description: Very low-priority issue for consideration

  # point labels
  - name: "points: 0"
    color: f2e63c
  - name: "points: 0.5"
    color: f2e63c
  - name: "points: 1"
    color: f2e63c
  - name: "points: 2"
    color: f2e63c
  - name: "points: 3"
    color: f2e63c
  - name: "points: 5"
    color: f2e63c
  - name: "points: 8"
    color: f2e63c
  - name: "points: 13"
    color: f2e63c
  - name: "points: 20"
    color: f2e63c
  - name: "points: 40"
    color: f2e63c
  - name: "points: 100"
    color: f2e63c

branches:
  - name: master
    # https://developer.github.com/v3/repos/branches/#update-branch-protection
    # Branch Protection settings. Set to null to disable
    protection:
      # Required. Require at least one approving review on a pull request, before merging. Set to null to disable.
      required_pull_request_reviews:
        # The number of approvals required. (1-6)
        required_approving_review_count: 2
        # Dismiss approved reviews automatically when a new commit is pushed.
        dismiss_stale_reviews: true
        # Blocks merge until code owners have reviewed.
        require_code_owner_reviews: true
        # Specify which users and teams can dismiss pull request reviews. Pass an empty dismissal_restrictions object to disable. User and team dismissal_restrictions are only available for organization-owned repositories. Omit this parameter for personal repositories.
        dismissal_restrictions:
          users: []
          teams: []
      # Required. Require status checks to pass before merging. Set to null to disable
      required_status_checks:
        # Required. Require branches to be up to date before merging.
        strict: true
        # Required. The list of status checks to require in order to merge into this branch
        contexts: []
      # Required. Enforce all configured restrictions for administrators. Set to true to enforce required status checks for repository administrators. Set to null to disable.
      enforce_admins: true
      # Required. Restrict who can push to this branch. Team and user restrictions are only available for organization-owned repositories. Set to null to disable.
      restrictions:
        apps: []
        users: []
        teams: []
